<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1vgt0fv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1vgt0fv/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1vgt0fv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1vgt0fv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1vgt0fv\appProdProjectContainer([
    'container.build_hash' => '1vgt0fv',
    'container.build_id' => '1c441c55',
    'container.build_time' => 1560861649,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1vgt0fv');
